name: CI

on: push

jobs:
  package:
    name: Run App Deployer
    runs-on: ubuntu-latest
    steps:
      - uses: corva-ai/app-deployer@edc1292e4314e337352c7d74ca983ee3cabc08e9
        with:
          api-url: ${{ secrets.CORVA_API_URL }}
          api-key: ${{ secrets.CORVA_API_KEY }}
          app-key: corva.sample-app-deployer
          notes: Sample App Deployment
          skip-analysis: false
          skip-testing: false
