name: CI

on: push

jobs:
  package:
    name: Run App Deployer
    runs-on: ubuntu-latest
    steps:
      - uses: corva-ai/app-deployer@14fb0d3895be9e56bbdca11b5f2b37c1ee2c3ab9
        with:
          api-url: ${{ secrets.CORVA_API_URL }}
          api-key: ${{ secrets.CORVA_API_KEY }}
          app-key: corva.sample-app-deployer
          notes: Sample App Deployment
          skip-analysis: false
          skip-testing: false
