name: CI

on: push

jobs:
  package:
    name: Run App Deployer
    runs-on: ubuntu-latest
    steps:
      - user: actions/checkout@v2
      - uses: corva-ai/app-deployer@develop
        with:
          api-url: ${{ secrets.CORVA_API_URL }}
          api-key: ${{ secrets.CORVA_API_KEY }}
          app-key: corva.sample_app_deployer
          notes: Sample App Deployment
          skip-analysis: false
          skip-testing: false
